version: '3.4'
services:
  mysqlcontainer:
    image: mysql:latest
    container_name: cpm-mysql
    ports:
      - 3306:3306
      - 9229:9229
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ../docs/carpark-setup.sql:/docker-entrypoint-initdb.d/carpark-setup.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=carpark
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=password
  devcontainer:
    container_name: cpm-dev
    command: /bin/sh -c "while sleep 1000; do :; done" && node --inspect=0.0.0.0:9229 ./bin/www
    volumes:
      - ..:/workspace:cached
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    network_mode: "host"
      # DISPLAY: $DISPLAY
    # ports:
    #   - 3000
    #   - 9229:9229
    # command: node --inspect=0.0.0.0:9229 ./bin/www
